// ====================================================================================
// Template: thingProperties_template.h
// Description:
//   This file serves as a placeholder for the actual 'thingProperties.h'
//   generated by Arduino IoT Cloud. Use this as a base structure when working
//   offline or in shared repositories.
//
// Instructions:
//   - Copy this file and rename it to 'thingProperties.h'
//   - Replace variable declarations and callbacks with actual Thing values
// ====================================================================================

#pragma once

// Mock property declarations (replace with actual generated values)
extern float dhtHumi;
extern float dhtTemp;

// Mock callback declarations (optional, if using onChange handlers)
// void onDhtHumiChange();
// void onDhtTempChange();

// Use ArduinoIoTCloud.begin() and initProperties() in main sketch